name: ebdeploy

on:
  push:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: "eu-west-2"
      DJANGO_CONFIGURATION: "Test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated version
      - name: Set up Python Environment
        uses: actions/setup-python@v4  # Updated version
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          pytest

  deploy:
    needs: [ test ]
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-2"
    steps:
      - uses: actions/checkout@v3  # Updated version

      - name: Install EB CLI using pip
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli

      - name: Initialize EB CLI
        run: |
          eb init -p python-3.7 my-app --region $AWS_DEFAULT_REGION

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy 
